### ISSUE TITLE
A shared storage setup where we have one Master and one Slave broker, without failback

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#154] opened 2024-08-22 12:29 UTC
##### SUMMARY
We would like to get a shared storage setup where we have one Master and one Slave broker, without failback. 

```
<ha-policy>
   <replication>
      <master>
        <allow-failback>false</allow-failback>
         <failover-on-shutdown>true</failover-on-shutdown>
      <master>
   </replication>
</ha-policy>

<ha-policy>
   <replication>
      <slave>
        <allow-failback>false</allow-failback>
         <failover-on-shutdown>true</failover-on-shutdown>
      <slave>
   </replication>
</ha-policy>
        
```
Currently this is not possible in the playbook. It is important for us to get this setup. Could you create this for us in the playbook. 

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment] 2024-08-22 12:42
Hello Robert; thanks for reporting. It will be made available for both shared store and replication

**Comment by RobertFloor** [comment] 2024-08-22 14:26
Please also review the systemctl template https://github.com/ansible-middleware/amq/blob/main/roles/activemq/templates/amq_broker.service.j2 for the scenario that you restart the master broker but it does not become active.

**Comment by guidograzioli** [comment] 2024-08-22 16:04
Sure, that will be addressed in a different PR.

**Closed** 2024-08-22 16:08 UTC
Labels: enhancement

**Comment by RobertFloor** [comment] 2024-08-23 11:10
Hi So this works but the systemd does not recognize the broker as correctly started since AMQ221001 is not reached if the master does not become active

**Comment by guidograzioli** [comment] 2024-08-23 12:46
I need to write the tests and also have many changes open, can you wait for 2.2.0 to be released? Currently the HEAD is a in a bit of rough state

**Comment by guidograzioli** [comment] 2024-08-26 10:18
Hello, the logs seem coherent with the allow_failback false; what is your expected behaviour?

**Comment by RobertFloor** [comment] 2024-08-26 10:26
So the problem is 
```
sudo systemctl restart amq-broker.service
Job for amq-broker.service failed because the control process exited with error code.
See "systemctl status amq-broker.service" and "journalctl -xe" for details.
```
Tis causes our pipeline to fail. It fails because
```
{% elif activemq_ha_enabled and (activemq_ha_role == 'master' or activemq_ha_role == 'primary') %}
ExecStartPost=/usr/bin/timeout {{ activemq_systemd_wait_for_timeout }} sh -c 'tail -n 15 -f {{ activemq.instance_home }}/log/artemis.log | sed "/AMQ221001/ q" && /bin/sleep {{ activemq_systemd_wait_for_delay }}'
{% else %}
```

But AMQ221001 is not reached when you restart the master but it does not become active

**Comment by guidograzioli** [comment] 2024-08-26 10:28
ah right; so as a quick workaround we could make both strings (master and slave) be acceptable as a started condition in the logs: that'd be quick to do and allow me to also allow to configure the string itself

**Comment by guidograzioli** [comment] 2024-08-26 11:00
https://github.com/ansible-middleware/amq/pull/156

**Comment by RobertFloor** [comment] 2024-08-26 12:12
Sorry it seems a little more complex then this. The Master logs  when starting as active server
```
2024-08-26 13:52:32,621 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started EPOLL Acceptor at 0.0.0.0:61616 for protocols [CORE,AMQP,OPENWIRE]
2024-08-26 13:52:32,641 INFO  [org.apache.activemq.artemis.core.server] AMQ221007: Server is now live
2024-08-26 13:52:32,642 INFO  [org.apache.activemq.artemis.core.server] AMQ221001: Apache ActiveMQ Artemis Message Broker version 2.28.0.redhat-00012 [asbf-test-internal, nodeID=562eba20-1741-11ee-a3cf-005056354120]
2024-08-26 13:52:32,647 INFO  [org.apache.activemq.artemis] AMQ241003: Starting embedded web server
2024-08-26 13:52:32,886 INFO  [org.apache.amq.hawtio.branding.PluginContextListener] Initialized redhat-branding plugin
2024-08-26 13:52:32,924 INFO  [org.apache.activemq.hawtio.plugin.PluginContextListener] Initialized artemis-plugin plugin
2024-08-26 13:52:33,760 INFO  [org.apache.activemq.artemis] AMQ241001: HTTP Server started at https://localhost:8161
2024-08-26 13:52:33,762 INFO  [org.apache.activemq.artemis] AMQ241002: Artemis Jolokia REST API available at https://localhost:8161/console/jolokia
2024-08-26 13:52:33,762 INFO  [org.apache.activemq.artemis] AMQ241004: Artemis Console available at https://localhost:8161/console
```
So in this case code AMQ221034 does not match

**Comment by guidograzioli** [comment] 2024-08-27 11:43
any luck with this?

**Comment by RobertFloor** [comment] 2024-08-27 13:04
I went for AMQ221010 AMQ221031 AMQ221007

**Comment by RobertFloor** [comment] 2024-08-27 16:00
Hi The changes after commit 0457e150b545f3ef229d6d9831b23c09eda0831c break our ssl settings. Somehow the expected name is localhost instead of the real hostnamen

**Comment by guidograzioli** [comment] 2024-08-27 17:56
Is it an acceptor or a connector? Can you provide the relevant parameters or the generated broker.xml for acceptors/connectors?

**Comment by guidograzioli** [comment] 2024-08-27 18:03
Ideally, I think you are defining your acceptor with `bind_address: "{{ activemq_host }}"` (the default); you should define activemq_host to match the hostname in the certificate (or set bind_address in the acceptor directly to the hostname).

**Comment by RobertFloor** [comment] 2024-08-29 10:37
Yes in the end it was a problem on our side. However I still wonder why you are selecting localhost as advertised connector. This document states: https://activemq.apache.org/components/artemis/documentation/latest/clusters. 
```
connector-ref
This is the connector which will be sent to other nodes in the cluster so they have the correct cluster topology.

This parameter is mandatory.
 ```
 So localhost does not make sense for us as it cannot be resolved by the other hosts

**Comment by guidograzioli** [comment] 2024-08-29 11:00
I know and agree it makes little sense. It has been the default generated value, in broker.xml, when running `artemis create` with a static list of nodes unfortunately; and since then I kept the default in the collection for sake of backwards compatibility. What i can do is document this mess better, promised.

**Comment by guidograzioli** [comment] 2024-08-29 11:01
And likely 'sanitize' the situation in 3.0 :)
